// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFBMJ3jLDz38MMKTfmIUDmu0TNbx7wUo0',
    appId: '1:548079551425:web:fb7a7fe5e87e1afb8b6540',
    messagingSenderId: '548079551425',
    projectId: 'noti-8532b',
    authDomain: 'noti-8532b.firebaseapp.com',
    storageBucket: 'noti-8532b.firebasestorage.app',
    measurementId: 'G-QV7K3359HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRe9yvcU9KaB7N-Ub9Wq8MVckNSBA2lmQ',
    appId: '1:548079551425:android:799b59b7a33977158b6540',
    messagingSenderId: '548079551425',
    projectId: 'noti-8532b',
    storageBucket: 'noti-8532b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjYWXO0SYhU5K-HqN5fZukAr_xTmVN1d4',
    appId: '1:548079551425:ios:c8753373863fc7908b6540',
    messagingSenderId: '548079551425',
    projectId: 'noti-8532b',
    storageBucket: 'noti-8532b.firebasestorage.app',
    iosClientId: '548079551425-72ujsmmkuvd9l2dphs666gkitldr0hvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjYWXO0SYhU5K-HqN5fZukAr_xTmVN1d4',
    appId: '1:548079551425:ios:c8753373863fc7908b6540',
    messagingSenderId: '548079551425',
    projectId: 'noti-8532b',
    storageBucket: 'noti-8532b.firebasestorage.app',
    iosClientId: '548079551425-72ujsmmkuvd9l2dphs666gkitldr0hvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFBMJ3jLDz38MMKTfmIUDmu0TNbx7wUo0',
    appId: '1:548079551425:web:0920ef6aa6546bc88b6540',
    messagingSenderId: '548079551425',
    projectId: 'noti-8532b',
    authDomain: 'noti-8532b.firebaseapp.com',
    storageBucket: 'noti-8532b.firebasestorage.app',
    measurementId: 'G-8VHE68M115',
  );
}
