const Map<String, String> enUS = {
  'notifications': 'Notifications',
  'search_placeholder': 'Search notifications...',
  'all': 'All',
  'unread': 'Unread',
  'read': 'Read',
  'settings': 'Settings',
  'theme': 'Theme',
  'language': 'Language',
  'light_mode': 'Light Mode',
  'dark_mode': 'Dark Mode',
  'system_mode': 'System Mode',
  'vietnamese': 'Vietnamese',
  'english': 'English',
  'no_notifications': 'No notifications yet',
  'error_occurred': 'An error occurred.',
  'try_again': 'Try again',
  'all_shown': 'All notifications shown',
  'notification_detail': 'Notification Detail',
  'not_found': 'Notification not found',
  'learn_more': 'Learn more',
  'notification_settings': 'Notification Settings',
  'appearance': 'Appearance',
  'badge_count': 'Badge count',
  'badge_desc': 'Show unread count badge on icon',
  'notification_type': 'Notification Type',
  'order_notif': 'Order',
  'promo_notif': 'Promotion',
  'system_notif': 'System',
  'current_language': 'Current language',
  'logout': 'Logout',
  'logout_confirm_title': 'Logout?',
  'logout_confirm_message': 'Are you sure you want to logout from this device?',
  'cancel': 'Cancel',
  'email': 'Email',
  'push_notification': 'Push Notifications',
  'sms': 'SMS',
  'display_mode': 'Display Mode',
  'light': 'Light',
  'dark': 'Dark',
  'version': 'Version',
  'welcome_back': 'Welcome Back',
  'login_to_continue': 'Login to continue',
  'gmail_label': 'Gmail',
  'password_label': 'Password',
  'login_button': 'Login',
  'register_button': 'Register',
  'or_login_with': 'Or login with',
  'login_failed': 'Login failed',
  'gmail_required': 'Please enter Gmail',
  'password_required': 'Please enter Password',
  'apple_login_not_implemented': 'Sign in with Apple will be available soon.',
  'failed_to_mark_all_read': 'Failed to mark all as read. Please try again.',
  'unauthorized_reason_expired': 'Session expired. Please login again.',
  'unauthorized_reason_rejected': 'Session rejected by server.',
  'unauthorized_reason_revoked': 'Your account was logged in elsewhere or revoked.',
  'logout_success': 'You have been logged out successfully.',
  'server_error': 'Server connection error',
  'auth_error': 'Authentication error',
  'facebook_error': 'Facebook connection error',
  'google_error': 'Could not get ID Token from Google.',
};
