const Map<String, String> viVN = {
  'notifications': 'Thông báo',
  'search_placeholder': 'Tìm kiếm thông báo...',
  'all': 'Tất cả',
  'unread': 'Chưa đọc',
  'read': 'Đã đọc',
  'settings': 'Cài đặt',
  'theme': 'Giao diện',
  'language': 'Ngôn ngữ',
  'light_mode': 'Chế độ sáng',
  'dark_mode': 'Chế độ tối',
  'system_mode': 'Theo hệ thống',
  'vietnamese': 'Tiếng Việt',
  'english': 'Tiếng Anh',
  'no_notifications': 'Chưa có thông báo nào',
  'error_occurred': 'Có lỗi xảy ra.',
  'try_again': 'Thử lại',
  'all_shown': 'Đã hiển thị tất cả thông báo',
  'notification_detail': 'Chi tiết thông báo',
  'not_found': 'Không tìm thấy thông báo',
  'learn_more': 'Xem thêm thông tin',
  'notification_settings': 'Cài đặt thông báo',
  'appearance': 'Hiển thị',
  'badge_count': 'Badge số lượng',
  'badge_desc': 'Hiển thị số thông báo chưa đọc trên icon',
  'notification_type': 'Loại thông báo',
  'order_notif': 'Đơn hàng',
  'promo_notif': 'Khuyến mãi',
  'system_notif': 'Hệ thống',
  'current_language': 'Ngôn ngữ hiện tại',
  'logout': 'Đăng xuất',
  'logout_confirm_title': 'Đăng xuất?',
  'logout_confirm_message':
      'Bạn có chắc chắn muốn đăng xuất khỏi thiết bị này không?',
  'cancel': 'Hủy',
  'email': 'Email',
  'push_notification': 'Thông báo đẩy',
  'sms': 'SMS',
  'display_mode': 'Chế độ hiển thị',
  'light': 'Sáng',
  'dark': 'Tối',
  'version': 'Phiên bản',
  'welcome_back': 'Chào mừng quay trở lại',
  'login_to_continue': 'Đăng nhập để tiếp tục',
  'gmail_label': 'Gmail',
  'password_label': 'Mật khẩu',
  'login_button': 'Đăng nhập',
  'register_button': 'Đăng ký',
  'or_login_with': 'Hoặc đăng nhập bằng',
  'login_failed': 'Đăng nhập thất bại',
  'gmail_required': 'Vui lòng nhập Gmail',
  'password_required': 'Vui lòng nhập Mật khẩu',
  'apple_login_not_implemented': 'Sẽ được triển khai sau (Apple)',
  'failed_to_mark_all_read':
      'Không thể đánh dấu tất cả đã đọc. Vui lòng thử lại.',
  'unauthorized_reason_expired':
      'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
  'unauthorized_reason_rejected': 'Phiên đăng nhập bị từ chối từ máy chủ.',
  'unauthorized_reason_revoked':
      'Tài khoản của bạn đã được đăng nhập từ nơi khác hoặc bị thu hồi.',
  'logout_success': 'Bạn đã đăng xuất thành công.',
  'server_error': 'Lỗi kết nối Server',
  'auth_error': 'Lỗi xác thực',
  'facebook_error': 'Lỗi kết nối Facebook',
  'google_error': 'Không thể lấy ID Token từ Google.',
};
